config/routes.rb
Rails.application.routes.draw do

  devise_for :users
 
  resources :users, :only => [:show, :index] do
    patch "giveRight", on: :member
    resources :addresses
    resources :ratings
    resources :biddings
  end

  resources :categories do
    get :autocomplete_category_name, :on => :collection
  end

  resources :products do
    patch "minbidded", on: :member
    patch "immediat", on: :member
    resources :ratings
    resources :biddings
  end

  root :to =>'home#index'

end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :ratable, polymorphic: true
	belongs_to :user

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
   before_action :set_rating, only: [:avgrate, :index, :show, :edit, :update, :destroy]

  def _index
    @context = context
    @ratings = Rating.where("ratable_id = ?", @context.id && "ratable_type = ?", @context.type).all
  end

  def show
  end

  def new
    @context = context
    @rating = @context.ratings.new
    authorize @rating
  end

  def create
    @context = context
    @rating = @context.ratings.new(rating_params)
    @rating.user = current_user
    authorize @rating

    if @rating.save
      redirect_to context_url(context), notice: "The notice has been successfully created."
    end
  end

  def edit
    authorize @rating
  end

  def update
      authorize @rating
      @context = context
      respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to context_url(context), notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def rating_params
    params.require(:rating).permit!
  end

  def context
    if params[:user_id]
      id = params[:user_id]
      type = 'User'
      User.find(params[:user_id])
    else
      id = params[:product_id]
      type = 'Product'
      Product.find(params[:product_id])
    end
  end 

  def context_url(context)
    if User === context
      user_path(context)
    else
      product_path(context)
    end
  end

  def set_rating
    @rating = Rating.find(params[:id])
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= bootstrap_form_for(@rating, as: :rating, url: user_ratings_path(@user.id), html: { method: :post }) do |a| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= a.text_field :title %><br />
  <%= a.text_field :comment %><br />
  <%= a.number_field :score %><br />
  <%= a.submit "Add" %>
<% end %>

app/views/ratings/_formedit.html.erb
<%= bootstrap_form_for(@rating, as: :rating, url: edit_user_rating_path(@rating.id, @rating.user)) do |a| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= a.text_field :title %><br />
  <%= a.text_field :comment %><br />
  <%= a.number_field :score %><br />
  <%= a.submit "Edit"  %>
<% end %>

app/views/ratings/_formproduct.html.erb
<%= bootstrap_form_for(@rating, as: :rating, url: product_ratings_path(@product.id), html: { method: :post }) do |a| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= a.text_field :title %><br />
  <%= a.text_field :comment %><br />
  <%= a.number_field :score %><br />
  <%= a.submit "Add" %>
<% end %>

app/views/ratings/_index.html.erb
<h3>Notice</h3>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Score</th>
      <th>Author</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @ratings.count == 0 %>
      <tr>
        <td colspan="4">
          No notice found.  Click the button above to add a new one.
        </td>
      </tr>
    <% else %>
      <% @ratings.each do |rating| %>
        <tr>
          <td><%= rating.title %></td>
          <td><%= rating.score %></td>
          <td><%= rating.user.firstname %></td>
          <td><%= link_to "Edit", edit_user_rating_path(rating.user_id, rating.id), class: "btn btn-default btn-xs" %>
          <%= link_to "Show", user_rating_path(rating.user_id, rating.id), class: "btn btn-default btn-xs" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/ratings/create.html.erb
<h1>Ratings#create</h1>
<p>Find me in app/views/ratings/create.html.erb</p>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>
<%= render 'formedit' %>
<%= link_to 'Show', @user ,class: "btn btn-default btn-xs"%> |
<%= link_to 'Back', @users, class: "btn btn-default btn-xs" %>

app/views/ratings/new.html.erb
<h1>Ratings#new</h1>
<p>Find me in app/views/ratings/new.html.erb</p>

app/views/ratings/show.html.erb
<h1>Ratings#show</h1>
<p>Find me in app/views/ratings/show.html.erb</p>

app/views/ratings/update.html.erb
<h1>Ratings#update</h1>
<p>Find me in app/views/ratings/update.html.erb</p>