config/routes.rb
Rails.application.routes.draw do

  devise_for :users
 
  resources :users, :only => [:show, :index] do
    patch "giveRight", on: :member
    resources :addresses
    resources :ratings
    resources :biddings
  end

  resources :categories do
    get :autocomplete_category_name, :on => :collection
  end

  resources :products do
    patch "minbidded", on: :member
    patch "immediat", on: :member
    resources :ratings
    resources :biddings
  end

  root :to =>'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_ancestry
	has_many :products

	def to_s
		name
	end

	def self.arrange_as_array(options={}, hash=nil)                                                                                                                                                            
		hash ||= arrange(options)
		arr = []
		hash.each do |node, children|
			arr << node
			arr += arrange_as_array(options, children) unless children.nil?
		end
    	arr
	end

	def name_for_selects
		"#{'-' * depth} #{name}"
	end

	def possible_parents
		parents = Category.arrange_as_array(:order => 'name')
		return new_record? ? parents : parents - subtree
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  autocomplete :category, :name

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.arrange_as_array({:order => 'name'})
=begin
    @categories = Category.all
=end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @prods = @category.products.all
  end

  # GET /categories/new
  def new
    @product = Product.new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= bootstrap_form_for @category do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
   <%= f.text_field :name, autocomplete: autocomplete_category_name_categories_path %>
   </div>
   <div class="field">
    <%= f.collection_select :parent_id, Category.arrange_as_array({:order => 'name'}, @category.possible_parents) , :id, :name_for_selects, :include_blank => "Select a category" %>
  </div> 
  <div class="field">
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_submenu_cats.html.erb
 <ul >
  <% categories.each do |sub_cat| %>
    <li ><%= link_to_unless_current sub_cat.name_for_selects, sub_cat%>
        <%= render './categories/submenu_cats', categories: sub_cat.children if sub_cat.children.present?%>
    </li>
  <% end %>
</ul>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.parent %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category, :class=>"btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Edit', edit_category_path(category), :class=>"btn btn-warning btn-xs" %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="container-fluid">
	<h3>Our products in the category : <%= @category.name %></h3>
  		<div class="row" >
			<% @prods[0,8].each do |p| %>
            
             <div class="col-md-4 ">
             	<div class="prodlist"><h4><%=p.title -%></h4>
             	Seller : <%=p.user.firstname %><br>
             	Current Price :<%= number_to_currency(p.price, precision: 2)-%><br>
                Immediat price :<%= number_to_currency(p.immediatprice, precision: 2)-%><br>
                Bid automatic :<%= number_to_currency(p.minbid, precision: 2)-%><br>
                End of bidding :<%= p.bidenddate -%><br>

             	Rating :<%= p.avgrate -%><br>
             	<td><%= link_to 'More', p, :class=>"btn btn-primary btn-xs" %></td>
             </div></div>
             <% end -%>
		</div>
</div>	