config/routes.rb
Rails.application.routes.draw do

  devise_for :users
 
  resources :users, :only => [:show, :index] do
    patch "giveRight", on: :member
    resources :addresses
    resources :ratings
    resources :biddings
  end

  resources :categories do
    get :autocomplete_category_name, :on => :collection
  end

  resources :products do
    patch "minbidded", on: :member
    patch "immediat", on: :member
    resources :ratings
    resources :biddings
  end

  root :to =>'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to	:user
	belongs_to	:category
	has_many	:ratings,	as: :ratable,	dependent: :destroy
	has_many	:biddings,  dependent: :destroy
	accepts_nested_attributes_for :biddings

	after_initialize do
  		if self.new_record?
    		# values will be available for new record forms.
    		self.purchased = false 
    		self.price = self.minbid
  		end
	end

	def avgrate
		@average = 0
		@ratings = Rating.where({'ratable_id': self.id, 'ratable_type': self.class})
		if @ratings.count == 0
			return "No rated"
		else
			@ratings.each do |rating|
			@average += rating.score
			end
			@average =  @average.to_f/@ratings.count
			return @average
		end
	end

	def autobid
		puts "self.minbid :" + self.minbid.to_s
	 	self.price = self.price + self.minbid
	end  

	def purchased?
		self.purchased = true
	end

	def prixmaxi
		if self.amount >= immediatprice || self.price >= immediatprice
			self.purchased?
		end
	end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_user!, :except => [:price, :index, :show]
	before_action :set_product, only: [:edit, :update, :destroy]


	# GET /products
	# GET /products.json
	def index
		@products = Product.all
	end


	# GET /products/1
	# GET /products/1.json
	def show
		@product = Product.find(params[:id])
		@ratings = Rating.where({"ratable_id": @product.id, "ratable_type": Product}).all
		@rating = Rating.new
		@biddings = Bidding.where({"product_id": @product.id})
		@bidding = Bidding.new
	end

	# GET /products/new
	def new
		@categories = Category.all
		@product = Product.new
		authorize @product
	end

	def minbidded
		@product = Product.find(params[:id])
		@product.autobid
		@product.save
		puts "new price : " + @product.price.to_s
		redirect_to @product, notice: 'Product was successfully updated with your bidding'
	end

	def immediat
		@product = Product.find(params[:id])
		@product.price = @product.immediatprice
		@product.save
		@product.purchased?
		redirect_to @product, notice: 'Product was successfully updated with your bidding'
	end

	# GET /products/1/edit
	def edit
		@categories = Category.all
		authorize @product
	end

  # POST /products
  # POST /products.json
  def create
	@product = Product.new(product_params)
	@product.user = current_user
	set_price 
	authorize @product
	respond_to do |format|
	  if @product.save
		format.html { redirect_to @product, notice: 'Product was successfully created.' }
		format.json { render :show, status: :created, location: @product }
	  else
		format.html { render :new }
		format.json { render json: @product.errors, status: :unprocessable_entity }
	  end
	end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
	authorize @product
	respond_to do |format|
	  if @product.update(product_params)
		format.html { redirect_to @product, notice: 'Product was successfully updated.' }
		format.json { render :show, status: :ok, location: @product }
	  else
		format.html { render :edit }
		format.json { render json: @product.errors, status: :unprocessable_entity }
	  end
	end
  end

  # DELETE /products/1
  # DELETE /products/1.json
	def destroy
		authorize @product
		@product.destroy
		respond_to do |format|
			format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

  private
	# Use callbacks to share common setup or constraints between actions.
	def set_product
		if user_signed_in? && Product.where(:user_id => current_user.id).count == 0
			redirect_to user_url, flash: {:notice => "You have no product registered, create the first !"}        
		else
			@product = Product.find(params[:id])
		end
	end

	def set_price
			@product.price = @product.startingprice
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def product_params
	  params.require(:product).permit(:user_id, :title, :description, :price, :image_url, :category_id, :startingprice, :immediatprice, :bidenddate, :minbid)
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= bootstrap_form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
      <div class="field">
          <%= f.collection_select(:category_id, @categories, :id, :name_for_selects, 
            {:prompt => "Select category" }, selected: @product.category, class: "form-control")  %>
      </div>
      <div class="field">
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.text_area :description %>
      </div>
      <div class="field" >
        <%= f.number_field :startingprice, step: 0.01 %>
      </div>
      <div class="field" >
        <%= f.number_field :minbid, step: 0.01 %>
      </div>
      <div class="field" >
        <%= f.number_field :immediatprice, step: 0.01 %>
      </div>
      <div class="field" >
        <%= f.date_field :bidenddate, step: 0.01 %>
      </div>
      <div class="field">
        <%= f.text_field :image_url %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>
<%= render 'form' %>
<%= link_to 'Show', @product ,class:"btn btn-default"%> 
<%= link_to 'Back', products_path, class:"btn btn-default" %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Products</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Seller</th>
      <th>Description</th
      <th>Price</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.user.firstname %></td>
        <td><%= product.description %></td>
        <td><%= number_to_currency(product.price, precision: 2) %></td>
        <td><%= product.image_url %></td>
        <td><%= link_to 'Show', product, :class=>"btn btn-default btn-xs" %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_product_path(product), :class=>"btn btn-default btn-xs" %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-default btn-xs" %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Product', new_product_path, :class=>"btn btn-success btn-md" %>
<% end -%>

app/views/products/indexbyuser.html.erb
<p id="notice"><%= notice %></p>


<h2>Listing Products of <%=current_user.firstname %></h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= number_to_currency(@product.price, precision: 2) %></td>
        <td><%= product.image_url %></td>
        <td><%= link_to 'Show', product, :class=>"btn btn-default btn-xs" %></td>
        <td><%= link_to 'Edit', edit_product_path(product), :class=>"btn btn-default btn-xs" %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-default btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<?php else: ?>
  You don't have products registered
<% end -%>

<%= link_to 'New Product', new_product_path, :class=>"btn btn-success btn-md" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h3 class="title_prod">
  <%= @product.title %>
</h3>

<div class="meta"> <%= @product.category %> - <%= @product.created_at.strftime("created at %B %d at %I:%M %p") %> by <strong><%= @product.user.firstname %></strong></div>

<div class="table_price_rating">
	<div class="price">
  		<%= number_to_currency(@product.price, precision: 2)  %>
	</div>
	<div class="rating">
		<strong>Rating:</strong>
		<%= @product.avgrate %>
	</div>
	<div class-"btnprice">
		<button type="button" class="btn btn-info" data-toggle="modal" data-target="#bidModal">
    		Custom Bidding
		</button>
	</div>
	<div class="btnprice">
		<%= bootstrap_form_for(@product, as: :auto_bid, url: minbidded_product_path(@product), html: { method: :patch }) do |p| %>
				<%= p.submit "Auto bid", class:"btn btn-success" %>
			<% end -%>
	</div>
	<div class = "btnprice">
		<%= bootstrap_form_for(@product, url: immediat_product_path(@product), html: { method: :patch }) do |p| %>
				<%= p.submit "Immediat buy", class:"btn btn-warning" %>
		<% end -%>
	</div>
</div>
<strong>Description:</strong>
	<%= @product.description %>
<div class="image_prod">
<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>
</div>

<button class="btn btn-default" onclick="$('#targetAddComment').toggle();">View notice</button>
<div id="targetAddComment" style="display: none">
<%= render './ratings/index' %>
</div> 

<% if @product.user != current_user %>
<button class="btn btn-default" onclick="$('#targetAdd').toggle();">Add an notice</button>
<div id="targetAdd" style="display: none">
<%= render './ratings/formproduct' %>
</div> 
<% end %>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_product_path(@product), class:"btn btn-default" %> |
<% end -%>
<%= link_to 'Back', products_path, class:"btn btn-default" %>


<!-- Modal -->
<div id="bidModal" tabindex="-1" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"> Custom bidding</h4>
      </div>
      <div class="modal-body">



<%= bootstrap_form_for(@bidding, as: :bidding, url: product_biddings_path(@product.id)) do |b| %>
  <% if @bidding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bidding.errors.count, "error") %> prohibited this bidding from being saved:</h2>

      <ul>
      <% @bidding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
  <h3>Choose the amount for bidding over the current price</h3>
      <div class="field" >
        <%= b.number_field :amount, step: 0.01 %>
      </div>
      <div class="actions">
        <%= b.submit %>
      </div>
  </div>
<% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>