config/routes.rb
Rails.application.routes.draw do

  devise_for :users
 
  resources :users, :only => [:show, :index] do
    patch "giveRight", on: :member
    resources :addresses
    resources :ratings
    resources :biddings
  end

  resources :categories do
    get :autocomplete_category_name, :on => :collection
  end

  resources :products do
    patch "minbidded", on: :member
    patch "immediat", on: :member
    resources :ratings
    resources :biddings
  end

  root :to =>'home#index'

end

app/views/layouts/_footer.html.erb
<footer></footer>

app/views/layouts/_header.html.erb
<div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag 'image2.jpg'%>
        <div class="carousel-caption">
          <h3>Titre 1</h3>
          <p>texte 1</p>
        </div>
      </div>
    
      <div class="item">
        <%= image_tag "image4.jpg" %>
        <div class="carousel-caption">
          <h3>Titre 2</h3>
          <p>texte 2</p>
        </div>
      </div>

      <div class="item">
        <%= image_tag "image3.png" %>
        <div class="carousel-caption">
          <h3>Titre 3</h3>
          <p>texte 3</p>
        </div>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
		 	<a class="navbar-brand" href="/">The Rails Braderie</a>
		</div>
		<div>
			<ul class="nav navbar-nav">
				<li><%= link_to "Products", products_path, :method => :get %></li>
				<% if user_signed_in? %>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
		  			<ul class="dropdown-menu">
						<li><%= link_to "All categories", categories_path, :method => :get %></li>
						<li><%= link_to 'New Category', new_category_path, class: "btn btn-success btn-md" %></li>
		  			</ul>
				</li>
				<% end -%>

				<li><%= link_to "Users", users_path, :method => :get %></li> 
				<% if user_signed_in? %>
				<li class="dropdown">
		  			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.firstname%>'s products <span class="caret"></span></a>
		  			<ul class="dropdown-menu">
			  			<% if user_signed_in? && current_user.products.count != 0 %>
						<li><%= link_to ""+current_user.firstname+"\'s sellings", user_path(current_user), :method => :get %></li> 
			  			<% end %>
			  			<li><%= link_to ""+current_user.firstname+"\'s buyings", product_path(current_user), :method => :get %></li> 
			  			<li><%= link_to ""+current_user.firstname+"\'s bidings", product_path(current_user), :method => :get %></li>
						<li><%= link_to 'New Product', new_product_path, class: "btn btn-success btn-md" %></li>
		  			</ul>
		  		</li>
		  		<% end -%>
	  		</ul>

			<ul class="nav navbar-nav navbar-right"> 
				<% if user_signed_in? %>
				<li><%= link_to ('<span class="glyphicon glyphicon-user"></span>  '+current_user.firstname+'').html_safe, user_path(current_user.id), :method => :get , class: 'btn btn-warning navbar-btn' %></li>
				<li><%= link_to '<span class="glyphicon glyphicon-log-out white"></span> Sign Out'.html_safe, destroy_user_session_path, :method => :delete, class: 'btn btn-danger navbar-btn' %></li>
				<% else %>
				<li><%= link_to '<span class="glyphicon glyphicon-log-in"></span> Sign In'.html_safe, new_user_session_path, :method => :get , class: 'btn btn-success navbar-btn' %></li>
				<li><%= link_to '<span class="glyphicon glyphicon-user"></span> Sign up'.html_safe, new_user_registration_path, :method => :get , class: 'btn btn-primary navbar-btn' %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_sidebar.html.erb
<aside>
	<div class="widget-cat" style="background-color:white">
		<div class="title_widget">Product categories</div>
		 <div id="submenu" >
			  <ul >
			  <% Category.roots.each do |category| %>
    			<li ><%= link_to category.name_for_selects, category %>
    				<%= render './categories/submenu_cats', categories: category.children if category.children.present? %>
				</li>		
			<% end -%>
			</ul>
		</div>
	</div>

	<div class="widget-search">
		<div class="title_widget">The search</div>
	</div>

	<div class="widget-infos">
		<div class="title_widget">The my-info</div>
	</div>

	<div class="widget">
	</div>

</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webapprails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>
<div class="container-fluid"> 
	<%= render "layouts/header" %>
	<%= render "layouts/navbar" %>
	<% if notice.present? %>
		<div class="alert alert-success">
		<p class="notice"><%= notice %></p>
		</div>
	<% end %>
	<% if alert.present? %>
		<div class="alert alert-danger">
		<p class="alert"><%= alert %></p>
		</div>
	<% end %>
	
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-lg-9">
			<section>
				<%= yield %>
			</section>
		</div>
		<div class="col-xs-12 col-lg-3">
			<%= render "layouts/sidebar" %>
		</div>
	</div>
	<%= render "layouts/footer" %>
</div>


</body>
</html>